#!/bin/sh

# PROVIDE: buzzkill
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="buzzkill"
rcvar="buzzkill_enable"
load_rc_config "${name}"

# defaults are set such that buzzkill is automatically enabled
: ${buzzkill_enable="YES"}
# assume buzzkill is cloned into the ec2-user's home directory
: ${buzzkill_dir="/home/ec2-user/buzzkill"}
: ${buzzkill_config="/usr/local/etc/config.buzzkill.json"}

pidfile="/var/run/buzzkill.pid"
command="/usr/sbin/daemon"
command_args="-cr -P ${pidfile} -u nobody /bin/sh -c \"${buzzkill_dir}/buzzkill.js -c ${buzzkill_config}\""
required_dirs="${buzzkill_dir}"
required_files="${buzzkill_config}"

METADATA_URL="http://169.254.169.254/latest/meta-data"
AWS_REGION=$(fetch -qo - "${METADATA_URL}/placement/availability-zone" | sed -e 's,[a-z]$,,')
PATH="$PATH:/usr/local/sbin:/usr/local/bin"
export AWS_REGION PATH

run_rc_command "$1"
